# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"IncrementalSplitter": "01_data.ipynb",
         "coco_stats": "01_data.ipynb",
         "gram": "02_loss.ipynb",
         "feat_m": "02_loss.ipynb",
         "VggFeats": "02_loss.ipynb",
         "layers": "02_loss.ipynb",
         "get_fs": "02_loss.ipynb",
         "get_stl_fs": "02_loss.ipynb",
         "get_cnt_fs": "02_loss.ipynb",
         "cnt_loss_fn": "02_loss.ipynb",
         "get_style_loss_fn": "02_loss.ipynb",
         "tv_loss_fn": "02_loss.ipynb",
         "FSTLoss": "02_loss.ipynb",
         "get_loss_func": "02_loss.ipynb",
         "TransformerNet": "03_models.ipynb"}

modules = ["data.py",
           "loss.py",
           "models.py"]

doc_url = "https://lgvaz.github.io/faststyle/"

git_url = "https://github.com/lgvaz/faststyle/tree/master/"

def custom_doc_links(name): return None
