# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_callback.ipynb (unless otherwise specified).

__all__ = ['SourceFeatsCallback', 'StyleFsCallback']

# Cell
from fastai2.basics import *
from fastai2.callback.all import *
from faststyle import *

# Cell
class SourceFeatsCallback(Callback):
  def __init__(self, stl_fts, cnt_fts): self.stl_fts, self.cnt_fts = stl_fts,cnt_fts

  def after_pred(self):
    self.learn.yb = (*self.yb, self.stl_fts, self.cnt_fts)

# Cell
class StyleFsCallback(Callback):
  def __init__(self, fns, get_fs, tfms=None):
    self.sims_fs = [get_fs(o) for o in _get_ims(fns)]

  def after_pred(self):
    self.learn.yb = (*self.yb, self.sims_fs)