# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_learner.ipynb (unless otherwise specified).

__all__ = ['style_learner']

# Cell
from fastai2.basics import *
from faststyle import *

# Cell
@delegates(Learner.__init__)
def style_learner(dls, style_fns, loss_func=None, arch=None, **kwargs):
  arch = arch or transformer_net()
  return Learner(dls, arch, loss_func=loss_func, metrics=LossMetrics(loss_func.metric_names),**kwargs)